"""Writes launcher/KeysData.cs: the game's 67 key-bound actions, for the
launcher's keys editor.

The list is the exe's own table at 0x865820 - 67 records of {id, name,
default key 1, default key 2} - joined with the names the game shows for
them (TRES_ACTIONS.trs, keyed by the AK_ name). The id is what the
registry value is called: the game keeps a binding as AK<id in hex>_1 and
_2 under HKCU\\Software\\Silver Style Entertainment\\Soldiers of Anarchy\\Settings,
0xFFFFFFFF for none. A key is a virtual-key code; a mouse button is
0x80000000 plus its number (0 left, 1 right, 2 middle, 3 wheel down, 4
wheel up), which is what the five actions whose default is their own id
are bound to.

Usage:
    python gen_keys_cs.py
"""
import os
import struct
import zipfile

import trs

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
EXE = os.path.join(ROOT, '_patched', 'soa.exe')
DATA = os.path.join(ROOT, '_patched', 'data.ubn')
OUT = os.path.join(HERE, 'launcher', 'KeysData.cs')
TABLE, COUNT = 0x865820, 67

GROUPS = [
    ('Camera', ('AK_PAN', 'AK_TRUCK', 'AK_PEDESTAL', 'AK_DOLLY', 'AK_TILT', 'AK_POW', 'AK_FREELOOK', 'AK_CAMERA',
                'AK_FOLLOW')),
    ('Selection', ('AK_SELECT', 'AK_GROUP', 'AK_CONTEXT', 'AK_COMMANDOSTACK')),
    ('Orders', ('AK_STOP', 'AK_LIEDOWN', 'AK_KNEEL', 'AK_STANDUP', 'AK_CHANGEKIMODE', 'AK_ALL_GET_OUT', 'AK_LOOT',
                'AK_ATTACK', 'AK_RELOAD', 'AK_THROW', 'AK_TOGGLE_FORMATION')),
    ('Minimap', ('AK_MINIMAP',)),
    ('Game', ('AK_PAUSE', 'AK_SAVE', 'AK_LOAD', 'AK_SCREENSHOT', 'AK_ESCAPE', 'AK_CHAT', 'AK_HINTS')),
    ('Help', ('AK_KEY_HELP', 'AK_MISSION_GOAL', 'AK_HELP', 'AK_DIALOG_HISTORY', 'AK_MP_STATISTIC')),
]


def group_of(name):
    for group, prefixes in GROUPS:
        if any(name.startswith(p) for p in prefixes):
            return group
    return 'Other'


def actions():
    exe = open(EXE, 'rb').read()
    pe = struct.unpack_from('<I', exe, 0x3C)[0]
    n = struct.unpack_from('<H', exe, pe + 6)[0]
    opt = struct.unpack_from('<H', exe, pe + 20)[0]
    secs = [struct.unpack_from('<IIII', exe, pe + 24 + opt + 40 * i + 8) for i in range(n)]

    def off(va):
        for vs, va0, rs, raw in secs:
            if va0 <= va - 0x400000 < va0 + vs:
                return va - 0x400000 - va0 + raw
        raise ValueError(hex(va))
    texts = dict(trs.parse(zipfile.ZipFile(DATA).read('data/GUIData/TextResource_eng/TRES_ACTIONS.trs')))
    out = []
    for i in range(COUNT):
        ident, name_at, k1, k2 = struct.unpack_from('<IIII', exe, off(TABLE + 16 * i))
        s = off(name_at)
        name = exe[s:exe.index(b'\0', s)].decode()
        out.append((ident, name, texts.get(name, name), k1, k2, group_of(name)))
    return out


def main():
    rows = actions()
    lines = ['// Generated by gen_keys_cs.py from the exe\'s action table (0x865820) and',
             '// TRES_ACTIONS.trs. Do not edit by hand.',
             'internal static class KeysData',
             '{',
             '    public static readonly KeyAction[] All =',
             '    {']
    for ident, name, text, k1, k2, group in rows:
        lines.append('        new KeyAction(0x%X, "%s", "%s", 0x%X, 0x%X, "%s"),'
                     % (ident, name, text.replace('"', '\\"'), k1, k2, group))
    lines += ['    };', '}', '']
    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(lines))
    print('wrote %s, %d actions' % (OUT, len(rows)))


if __name__ == '__main__':
    main()
