"""Writes weapons.md: what every ammunition, weapon and vehicle in Data.set
does in numbers - damage, blast radius, armour, range, rate of fire.

The fields come out of dataset.py; what they mean was read off the code
and checked with the gun (weapons.md says how). Anything not established
is printed under its field number, so the table stays honest.

Usage:
    python gen_weapons_doc.py            writes ../weapons.md
    python gen_weapons_doc.py --print    to stdout
"""
import os
import sys

import dataset

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, '..', 'weapons.md')

EFFECT = {0: 'none', 1: 'fire', 2: 'bullet', 3: 'HE', 4: 'HEAT', 5: 'heavy HE'}
GUIDANCE = {0: 'ballistic', 1: 'straight', 2: 'guided'}


def n(r, i):
    return dataset.number(r, i) if i < r['fields'] else ''


def name(r):
    return r['name'].replace('|', '/')


def ammo_rows(records):
    rows = ['| # | id | name | weight | vs soldiers | vs vehicle hp | vs armour | penetrates below | blast radius | effect | flight | speed | stack | f11 |',
            '|---|---|---|---|---|---|---|---|---|---|---|---|---|---|']
    for r in records:
        if r['type'] != 1:
            continue
        rows.append('| %d | `%s` | %s | %s | %s–%s | %s–%s | %s–%s | %s | %s | %s | %s | %s | %s | %s |' % (
            r['number'], r['id'], name(r), n(r, 1), n(r, 2), n(r, 3), n(r, 4), n(r, 5), n(r, 6), n(r, 7), n(r, 8),
            n(r, 9), EFFECT.get(r['ints'][10], str(r['ints'][10])), GUIDANCE.get(r['ints'][14], str(r['ints'][14])),
            n(r, 15), n(r, 13), n(r, 11)))
    return rows


def weapon_rows(records):
    by_number = {r['number']: r for r in records}
    rows = ['| # | id | name | range | min range | rounds/min | aim | weight | f13 | f14 | f15 | f16 | ammunition | speed | salvo |',
            '|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|']
    for r in records:
        if r['type'] != 2:
            continue
        count = r['ints'][17] if r['fields'] > 17 else 0
        ammo = []
        for k in range(count):
            i = 18 + k
            if i < r['fields']:
                a = by_number.get(r['ints'][i])
                ammo.append('`%s`' % a['id'] if a else str(r['ints'][i]))
        after = 18 + count
        rows.append('| %d | `%s` | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s |' % (
            r['number'], r['id'], name(r), n(r, 2), n(r, 3), n(r, 4), n(r, 6), n(r, 1), n(r, 13), n(r, 14), n(r, 15),
            n(r, 16), ', '.join(ammo) or '—', n(r, after), n(r, after + 1)))
    return rows


def vehicle_rows(records):
    rows = ['| # | id | name | hit points | armour | speed | seats | f3 | f9 |',
            '|---|---|---|---|---|---|---|---|---|']
    for r in records:
        if r['type'] != 3:
            continue
        rows.append('| %d | `%s` | %s | %s | %s | %s | %s | %s | %s |' % (
            r['number'], r['id'], name(r), n(r, 5), n(r, 2), n(r, 4), n(r, 6), n(r, 3), n(r, 9)))
    return rows


HEAD = '''# Weapons, ammunition and armour, in numbers

Everything the game knows about what a shot does comes from `Data.set`
([dataset-format.md](dataset-format.md)); this page names the fields and
lists them. Generated by [tools/gen_weapons_doc.py](tools/gen_weapons_doc.py);
[tools/gen_weapons_web.py](tools/gen_weapons_web.py) makes the same tables
into one web page with the game's own pictures, sortable and searchable.
The M34 grenade (150, its round 151) is ours, not the game's - see
[architecture.md](architecture.md), "A new weapon"; it is listed as the game
with the package's loose `Data.set` sees it.

## How a hit is resolved

Read off the code and checked with the gun (a soldier of the squad shooting
at a monk, a Hummer and a BTR-80 while the ammunition's fields were
changed in memory - [tools/play_bot.py](tools/play_bot.py) gives the
orders, `scan_memory` writes the fields).

Every unit carries two pools: **hit points** (`+0xD0` the most, `+0xD4`
what is left) and **armour** (`+0xD8`/`+0xDC`). A soldier's armour is his
vest - the heavy vest counts 80, the light one 40, none 0; a vehicle's is
the `armour` column below. A soldier's hit points are his own (100 for
the mission's own men and women, more for the squad's veterans - Feodor
Wostow has 475); a vehicle's the `hit points` column.

One hit with a round of ammunition, `TakeDamage` (`0x57CDB0`, then
`0x57CE70`):

* the **armour** pool loses `vs armour` (a random value between the two);
* the **hit points** lose something only when the armour left is below
  `penetrates below` - then `vs soldiers` for a soldier (unit kind 3 or 4),
  `vs vehicle hp` for anything else.

So an AK-74 round (armour 3–4, penetrates below 4) has to strip a BTR-80's
1500 armour before its 2–3 points of hit-point damage ever count, while an
RPG-7 grenade (armour 1400–1800, penetrates below 500) takes a T-55's 2500
armour in two hits and then does 150–200 to its 100 hit points. Against a
monk with no vest every round is a hit on the hit points: 9–11 from the
AK-74, ten rounds to a kill, watched live.

An **explosion** (`0x56D9A0`) reaches every object within `blast radius`
and scales the four values by `1 - distance / radius`, with the top of
each range; a rocket that hits an object directly also does its direct
damage first. The `fire` effect (Plamja incendiary, Molotov) burns for a
while instead, a tenth of the values per tick to whoever stands in it.

The **difficulty** scales what the human player's units take
(`0x5807F0`): ×0.5 on the easiest, ×0.75, ×1, ×1.25 on the hardest. The
enemy takes full damage on every setting.

## Ammunition

`effect` is field 10 (what the impact looks like and does: 2 a bullet, 3 an
HE burst, 4 a shaped charge, 5 a heavy burst, 1 fire, 0 nothing - smoke and
flares); `flight` is field 14 (0 ballistic, 1 straight, 2 guided); `speed`
(field 15) is the projectile's, in world units per second - bullets are
near enough instant. `f11` is not understood (1 everywhere but the 14.5 mm
rounds).

'''

MIDDLE_WEAPONS = '''
## Weapons

`range` and `min range` are fields 2 and 3 in world units (one unit is one
map cell); `rounds/min` is field 4; `aim` (field 6) grows with the time a
shot takes to line up - 0.7 s for the AK-74, 2.5 for the Dragunov, 5 for
the RPG-7, near zero for the vehicle guns; `speed` and `salvo` are the two
fields after the ammunition list (a rocket pod's salvo is its number of
tubes). `f13`–`f16` are not understood: f14–f16 look like three hit
chances in percent (5/10/35 for the Beretta, 100/100/100 for the SA-7), f13
is 5 for most small arms and 60 for the tank guns.

'''

MIDDLE_VEHICLES = '''
## Vehicles

The `armour` (field 2) and `hit points` (field 5) are what the units carry
in the mission, checked live: Hummer 50/200, BTR-80 120/1500, BMP-1 90/2000,
T-55 100/2500. `speed` is field 4, `seats` field 6. `f3` and `f9` are not
understood (f9 is 60 for the ground vehicles and 100 for the aircraft -
sight range, perhaps).

'''


def build():
    records = dataset.load(with_m34=True)
    return (HEAD + '\n'.join(ammo_rows(records)) + '\n' + MIDDLE_WEAPONS + '\n'.join(weapon_rows(records)) + '\n'
            + MIDDLE_VEHICLES + '\n'.join(vehicle_rows(records)) + '\n')


def main():
    text = build()
    if '--print' in sys.argv:
        sys.stdout.write(text)
        return
    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write(text)
    print('wrote', os.path.abspath(OUT))


if __name__ == '__main__':
    main()
